spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  sql.init.mode: always

logging:
  level:
    root: DEBUG

jwt:
  password: sdfasdfasfdaasdfsdfasdfasfdaasdfasdfasdfasdfasdf # 48 * 6 = 288